spring:
  application:
    name: ktv
  mail:
    host: smtp.gmail.com
    port: 587
    username: cbbmmzx
    password: kofc hesi xxqh imof
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ktv
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8089
servlet:
  multipart:
    enabled: true
    max-file-size: 2MB
    max-request-size: 5MB
security:
  jwt:
    expiration-minutes: 30
    secret-key: dGhpcyBpcyBteSBzZWN1cmUga2V5IGFuZCB5b3UgY2Fubm90IGhhY2sgaXQ=
  upload:
    directory: uploads

app:
  token:
    secret: m#MySecretGGWP2021
    issuer: BackendService
  email:
    from: cbbmmzx@gmail.com
